# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20170617_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
